{
  config,
  lib,
  ...
}:
with lib; {
  imports = [
    ./niri.nix
    ./hyprland.nix
    ./waybar.nix
    ./mako.nix
    ./fuzzel.nix
    ./rofi.nix
    ./swaybg.nix
    ./swayidle.nix
    ./swaylock.nix
    ./thunar.nix
    ./xwayland-satellite.nix
    ./greetd.nix
    ./firefox.nix
    ./google-chrome.nix
    ./zen-browser.nix
    ./screenshot.nix
    ./clipboard.nix
    ./noctalia.nix
    ./sierra-chart.nix
    ./tradecopia.nix
    ./obs.nix
    ./chromium.nix
  ];
}
