{
  config,
  lib,
  pkgs,
  pkgs-stable,
  pkgs-edge,
  pkgs-unstable,
  ...
}:
with lib; let
  cfg = config.modules.communication.vesktop;
  themeEnabled = config.modules.theme.enable or false;
  palette = config.modules.theme.palette or {};
  channels = import ../lib/channels.nix {
    inherit lib pkgs pkgs-stable pkgs-edge pkgs-unstable;
  };
in
  channels.mkChannelModule {
    inherit cfg;
    optionPath = [ "modules" "communication" "vesktop" ];
    description = "Vesktop - Custom Discord client with Vencord built-in";
    mkConfig = {channelPkgs, ...}: {
      environment.systemPackages = [ channelPkgs.vesktop ];

      home-manager.sharedModules = mkIf themeEnabled [
        ({...}: {
          # Vencord custom CSS theme synced to system palette
          home.file.".config/vesktop/themes/system-theme.css".text = ''
            /**
             * System Theme: ${palette.name or "custom"}
             * Auto-generated by titan-os theme module
             */

            .theme-dark {
              /* Background */
              --background-primary: ${palette.base} !important;
              --background-secondary: ${palette.mantle} !important;
              --background-secondary-alt: ${palette.crust} !important;
              --background-tertiary: ${palette.crust} !important;
              --background-accent: ${palette.surface0} !important;
              --background-floating: ${palette.mantle} !important;
              --background-modifier-hover: ${palette.surface0} !important;
              --background-modifier-active: ${palette.surface1} !important;
              --background-modifier-selected: ${palette.surface0} !important;

              /* Text */
              --text-normal: ${palette.text} !important;
              --text-muted: ${palette.subtext0} !important;
              --text-link: ${palette.primary} !important;
              --header-primary: ${palette.text} !important;
              --header-secondary: ${palette.subtext1} !important;
              --interactive-normal: ${palette.subtext1} !important;
              --interactive-hover: ${palette.text} !important;
              --interactive-active: ${palette.text} !important;
              --interactive-muted: ${palette.surface2} !important;

              /* Accent / Brand */
              --brand-experiment: ${palette.primary} !important;
              --brand-experiment-560: ${palette.primary} !important;

              /* Channels */
              --channels-default: ${palette.subtext1} !important;
              --channel-icon: ${palette.subtext0} !important;

              /* Scrollbar */
              --scrollbar-thin-thumb: ${palette.surface1} !important;
              --scrollbar-auto-thumb: ${palette.surface1} !important;
              --scrollbar-auto-track: ${palette.crust} !important;

              /* Status */
              --status-positive: ${palette.success} !important;
              --status-warning: ${palette.warning} !important;
              --status-danger: ${palette.error} !important;

              /* Input */
              --input-background: ${palette.surface0} !important;
              --channeltextarea-background: ${palette.surface0} !important;

              /* Misc */
              --activity-card-background: ${palette.mantle} !important;
              --deprecated-card-bg: ${palette.surface0} !important;
              --modal-background: ${palette.base} !important;
              --modal-footer-background: ${palette.mantle} !important;
            }
          '';
        })
      ];
    };
  }
